### ISSUE TITLE
Module configuration broken on macOS-arm64

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#2422]
There appears to be an issue with developer module support on macOS-arm64. (Obviously related to #2247 but starting a new thread because the other one is long enough already.)

MRtrix3 installed from source, using default `./configure & ./build` with Qt5 and Eigen installed through homebrew. To reproduce the issue:
```
➜  ~ mkdir -p test-module/cmd 
➜  ~ cd test-module
➜  test-module cp ../mrtrix3/cmd/tckinfo.cpp cmd/
➜  test-module ln -s ../mrtrix3/build
➜  test-module ./build
```
produces a long list of linker issues, all to do with the target architecture. From `build.log`:
```
...
  (1/3) [CC] tmp/cmd/tckinfo.o
 clang++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=12.1 -DMRTRIX_WORD64 -DMRTRIX_HAVE_EIGEN_UNSUPPORTED_SPECIAL_FUNCTIONS -Wall -O3 -DNDEBUG -DMRTRIX_PROJECT -Isrc -I../mrtrix3/src -I../mrtrix3/core -Icmd -idirafter /opt/homebrew/Cellar/eigen/  3.4.0_1/include/eigen3 -DEIGEN_DONT_PARALLELIZE cmd/tckinfo.cpp -o tmp/cmd/tckinfo.o
 (2/3) [CC] tmp/src/project_version.o
 clang++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=12.1 -DMRTRIX_WORD64 -DMRTRIX_HAVE_EIGEN_UNSUPPORTED_SPECIAL_FUNCTIONS -Wall -O3 -DNDEBUG -DMRTRIX_PROJECT -Isrc -I../mrtrix3/src -I../mrtrix3/core -Icmd -idirafter /opt/homebrew/Cellar/eigen/  3.4.0_1/include/eigen3 -DEIGEN_DONT_PARALLELIZE src/project_version.cpp -o tmp/src/project_version.o
 (3/3) [LB] bin/tckinfo
 clang++ ../mrtrix3/tmp/src/dwi/tractography/rng.o ../mrtrix3/tmp/src/exec_version.o ../mrtrix3/tmp/src/dwi/tractography/file_base.o tmp/src/project_version.o ../mrtrix3/   tmp/src/dwi/tractography/roi.o ../mrtrix3/tmp/src/dwi/tractography/properties.o ../mrtrix3/tmp/src/dwi/tractography/seeding/list.o tmp/cmd/tckinfo.o -lmrtrix -mmacosx-version-min=12.1 -lz -Wl,-rpath,@loader_path/../../mrtrix3/lib -L../mrtrix3/lib -o bin/tckinfo

 ERROR: (3/3) [LB] bin/tckinfo

 clang++ ../mrtrix3/tmp/src/dwi/tractography/rng.o ../mrtrix3/tmp/src/exec_version.o ../mrtrix3/tmp/src/dwi/tractography/file_base.o tmp/src/project_version.o ../mrtrix3/   tmp/src/dwi/tractography/roi.o ../mrtrix3/tmp/src/dwi/tractography/properties.o ../mrtrix3/tmp/src/dwi/tractography/seeding/list.o tmp/cmd/tckinfo.o -lmrtrix -mmacosx-version-min=12.1 -lz -Wl,-rpath,@loader_path/../../mrtrix3/lib -L../mrtrix3/lib -o bin/tckinfo

 failed with output

 ld: warning: ignoring file ../mrtrix3/tmp/src/exec_version.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/tmp/src/dwi/tractography/rng.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/tmp/src/dwi/tractography/file_base.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/tmp/src/dwi/tractography/roi.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/tmp/src/dwi/tractography/seeding/list.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/tmp/src/dwi/tractography/properties.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
 ld: warning: ignoring file ../mrtrix3/lib/libmrtrix.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 Undefined symbols for architecture x86_64:
   "MR::ProgressBar::display_func", referenced from:
       run() in tckinfo.o
   "MR::ProgressBar::progressbar_active", referenced from:
       run() in tckinfo.o
...
```
The compiler and linker commands are identical to those in `../mrtrix3/build.log`, so I don't understand why the module is trying to build x86 binaries when their (shared) config is set up to build for arm64. Any ideas I while keep digging?

**Comment by jdtournier** [comment]
Have you tried a `./build clean` in the base MRtrix install? It looks like there may be some old objects generated in the base `src/` folder that may have been built for a different target, potentially with a different config at the time?

**Comment by dchristiaens** [comment]
It's a fresh install.. The only "fix" I've found so far is to build with a `./configure -nogui`, so it appears to be Qt-related.

Oddly though, after doing this, a new `./configure` call also fails on a similar linking error:
```
EXEC <<
 CMD: clang++ -mmacosx-version-min=12.2 -lz qt_moc.o qt.o -o qt -stdlib=libc++ -headerpad_max_install_names -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-    min=12.2 -Wl,-rpath,@executable_path/../Frameworks -F/opt/homebrew/Cellar/qt@5/5.15.2_1/lib -framework QtOpenGL -framework QtSvg -framework QtWidgets -framework QtGui -framework AppKit -    framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL
 EXIT: 1
 STDERR:
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtOpenGL.framework/QtOpenGL, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtSvg.framework/QtSvg, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtWidgets.framework/QtWidgets, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtGui.framework/QtGui, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtNetwork.framework/QtNetwork, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 ld: warning: ignoring file /opt/homebrew/Cellar/qt@5/5.15.2_1/lib/QtCore.framework/QtCore, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
 Undefined symbols for architecture x86_64:
...
```
Clearly, something has changed in my Qt/Homebrew setup between yesterday and today. Though I can't think what it could be...
